export const translations = {
  en: {
    // ==================== COMMON ====================
    common: {
      continue: 'Continue',
      submit: 'Submit',
      cancel: 'Cancel',
      save: 'Save',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      ok: 'OK',
      delete: 'Delete',
      edit: 'Edit',
      confirm: 'Confirm',
      back: 'Back',
      retry: 'Retry',
      free: 'Free',
      sar: 'SAR',
      male: 'Male',
      female: 'Female',
      yes: 'Yes',
      no: 'No',
      days: 'Days',
      day: 'Day',
      or: 'OR',
      primary: 'Primary',
      active: 'Active',
      paused: 'Paused',
      expired: 'Expired',
      cancelled: 'Cancelled',
      show: 'Show',
      hide: 'Hide',
      cal: 'cal',
    },

    // ==================== ONBOARDING ====================
    onboarding: {
      title1: 'Fresh & Healthy Meals',
      subtitle1: 'Get delicious, nutritious meals delivered to your doorstep daily',
      title2: 'Flexible Subscriptions',
      subtitle2: 'Choose from various meal plans that fit your lifestyle',
      title3: 'Track Your Orders',
      subtitle3: 'Real-time tracking of your meal preparation and delivery',
      skip: 'Skip',
      next: 'Next',
      getStarted: 'Get Started',
    },

    // ==================== AUTH ====================
    auth: {
      login: 'Login',
      signup: 'Sign Up',
      phoneNumber: 'Phone Number',
      enterPhone: 'Enter your phone number',
      password: 'Password',
      enterPassword: 'Enter your password',
      forgotPassword: 'Forgot Password?',
      dontHaveAccount: "Don't have an account?",
      alreadyHaveAccount: 'Already have an account?',
      continueWithGoogle: 'Continue with Google',
      continueWithApple: 'Continue with Apple',
      fullName: 'Full Name',
      enterName: 'Enter your full name',
      email: 'Email',
      enterEmail: 'Enter your email',
      confirmPassword: 'Confirm Password',
      agreeTerms: 'I agree to Terms & Conditions',
      welcome: "Welcome to Let'Salad",
      enterPhoneSubtitle: 'Enter your phone number to continue',
      freshMeals: 'Fresh meals, delivered daily',
      createAccount: 'Create your account to get started',
      failedSendOtp: 'Failed to send OTP',
      failedSendOtpRetry: 'Failed to send OTP. Please try again.',
    },

    // ==================== OTP ====================
    otp: {
      title: 'Enter Verification Code',
      sentTo: "We've sent a 6-digit code to",
      resendIn: 'Resend code in',
      resendCode: 'Resend Code',
      verify: 'Verify & Continue',
      invalidOtp: 'Invalid OTP',
      invalidOtpMessage: 'Invalid OTP code. Please try again.',
      incorrectOtp: 'The OTP code you entered is incorrect.',
      otpResent: 'OTP has been resent to your phone',
      failedResend: 'Failed to resend OTP',
      failedResendRetry: 'Failed to resend OTP. Please try again.',
    },

    // ==================== PROFILE ====================
    profile: {
      completeTitle: 'Complete Your Profile',
      completeSubtitle: 'Help us personalize your meal experience',
      fullName: 'Full Name',
      enterFullName: 'Enter your full name',
      emailAddress: 'Email Address',
      emailPlaceholder: 'your.email@example.com',
      sex: 'Sex',
      weightKg: 'Weight (kg)',
      heightCm: 'Height (cm)',
      age: 'Age',
      saveChanges: 'Save Changes',
      profileUpdated: 'Profile updated successfully',
      failedSaveProfile: 'Failed to save profile',
      failedSaveProfileRetry: 'Failed to save profile. Please try again.',
      failedUpdateProfile: 'Failed to update profile',
      failedUpdateProfileRetry: 'Failed to update profile. Please try again.',
    },

    // ==================== PREFERENCES ====================
    preferences: {
      subscribingForTitle: 'Who are you subscribing for?',
      subscribingForSubtitle: "Let's tailor the experience to meet your needs",
      forMe: 'For me',
      forMeDesc: 'Personalized meal plans for your fitness goals',
      forKids: 'For kids',
      forKidsDesc: 'Healthy meal plans for kids aged 2-12',
      genderTitle: "What's your gender?",
      genderSubtitle: 'We will use this to calculate your daily calorie needs',
      allergiesTitle: 'Do you have any food allergies?',
      goalTitle: "What's your goal?",
      eatHealthy: 'Eat healthy',
      eatHealthyDesc: 'Here to make it easier to eat healthier',
      loseWeight: 'Lose Weight',
      loseWeightDesc: 'Safe and healthy rate of weight & fat loss',
      gainWeight: 'Gain Weight',
      gainWeightDesc: 'Safe and healthy rate of weight gain',
      buildMuscle: 'Build Muscle',
      buildMuscleDesc: 'Gain strength while minimizing fat gain',
      maintainWeight: 'Maintain Weight',
      maintainWeightDesc: 'Stay in shape with the right calories',
      mealTypeTitle: 'What kind of meals do you prefer?',
      mealTypeSubtitle: "You'll have access to the full menu but select one to personalise your experience",
      balanced: 'Balanced',
      balancedDesc: 'Provides the nutrients your body needs to thrive',
      lowCarb: 'Low-Carb',
      lowCarbDesc: 'Low in carbs, but high in healthy fats, and non-starchy veggies',
      highProtein: 'High Protein',
      highProteinDesc: 'Boosts muscle strength and vitality with lean proteins',
      protein: 'Protein',
      carbs: 'Carbs',
      fat: 'Fat',
      complete: 'Complete',
      failedSavePreferences: 'Failed to save preferences',
      failedSavePreferencesRetry: 'Failed to save preferences. Please try again.',
    },

    // ==================== PROFILE SCREEN (Menu) ====================
    profileScreen: {
      editProfile: 'Edit Profile',
      changePassword: 'Change Password',
      deliveryAddress: 'Delivery Address',
      paymentMethods: 'Payment Methods',
      helpSupport: 'Help & Support',
      termsConditions: 'Terms & Conditions',
      privacyPolicy: 'Privacy Policy',
      deleteAccount: 'Delete Account',
      logout: 'Logout',
      language: 'Language',
      deleteAccountTitle: 'Delete Account',
      deleteAccountMessage: 'Are you sure you want to delete your account? This action cannot be undone.',
      failedDeleteAccount: 'Failed to delete account.',
    },

    // ==================== CHANGE PASSWORD ====================
    changePassword: {
      currentPassword: 'Current Password',
      enterCurrentPassword: 'Enter current password',
      newPassword: 'New Password',
      enterNewPassword: 'Enter new password',
      confirmNewPassword: 'Confirm New Password',
      confirmNewPasswordPlaceholder: 'Confirm new password',
      passwordsNoMatch: 'Passwords do not match',
      newPasswordsNoMatch: 'New passwords do not match',
      passwordMinLength: 'New password must be at least 6 characters',
      changePassword: 'Change Password',
      passwordChanged: 'Password changed successfully',
      failedChangePassword: 'Failed to change password',
      failedChangePasswordRetry: 'Failed to change password. Please try again.',
    },

    // ==================== MENU ====================
    menu: {
      title: 'Menu',
      subtitle: 'Choose your favorite meals',
      loadingMenu: 'Loading menu...',
      noItems: 'No items available',
      subscribe: 'Subscribe for',
    },

    // ==================== SUBSCRIPTIONS ====================
    subscription: {
      mySubscriptions: 'My Subscriptions',
      loadingSubscriptions: 'Loading your subscriptions...',
      noSubscriptions: 'No Active Subscriptions',
      noSubscriptionsDesc: "You don't have any active subscriptions yet.",
      chooseToStart: 'Choose a plan to get started!',
      chooseSubscription: 'Choose a Subscription',
      manageSubtitle: 'Manage your active meal plans',
      plan: 'Plan:',
      mealsRemaining: 'Meals Remaining:',
      daysRemaining: 'Days Remaining:',
      manageSubscription: 'Manage Subscription',
      addMore: '+ Add More Subscriptions',
      failedLoadSubscriptions: 'Failed to load subscriptions. Please try again.',
    },

    // ==================== SUBSCRIPTION PACKAGES ====================
    packages: {
      title: 'Choose Your Plan',
      subtitle: 'Select a subscription package that fits your lifestyle',
      loadingPackages: 'Loading packages...',
      noPackages: 'No packages available for this plan',
      recommended: 'Recommended',
      includes: 'Includes:',
      selectPlan: 'Select Plan',
      failedLoadPackages: 'Failed to load subscription plans. Please try again.',
    },

    // ==================== MANAGE SUBSCRIPTION ====================
    manageSubscription: {
      loadingSubscription: 'Loading subscription...',
      subscriptionPaused: 'Subscription Paused',
      resumesIn: 'Resumes in',
      on: 'on',
      subscriptionDetails: 'Subscription Details',
      package: 'Package',
      plan: 'Plan',
      duration: 'Duration',
      daysRemaining: 'Days Remaining',
      mealsRemaining: 'Meals Remaining',
      startDate: 'Start Date',
      endDate: 'End Date',
      pauseDaysUsed: 'Pause Days Used',
      status: 'Status',
      deliveryInfo: 'Delivery Info',
      deliveryAddress: 'Delivery Address',
      deliveryZone: 'Delivery Zone',
      payment: 'Payment',
      mealPlanning: 'Meal Planning',
      selectMeals: 'Select Your Meals',
      selectMealsDesc: 'Choose meals for the next 5 days',
      mealUpdateNote: 'You can update meal selections up to 8:00 PM the day before delivery',
      actions: 'Actions',
      pauseSubscription: 'Pause Subscription',
      pauseDaysUsedAction: 'pause days used',
      resumeSubscription: 'Resume Subscription',
      resumeDesc: 'Resume deliveries now',
      failedLoadDetails: 'Failed to load subscription details.',
      pauseLimitReached: 'Pause Limit Reached',
      pauseLimitMessage: 'You have already used all',
      pauseDaysForSub: 'pause days for this subscription.',
      youHave: 'You have',
      pauseRemaining: 'remaining',
      subscriptionPausedFor: 'Your subscription has been paused for',
      failedPause: 'Failed to pause subscription.',
      failedPauseRetry: 'Failed to pause subscription. Please try again.',
      subscriptionResumed: 'Subscription Resumed',
      subscriptionActive: 'Your subscription is now active again.',
      failedResume: 'Failed to resume subscription.',
      failedResumeRetry: 'Failed to resume subscription. Please try again.',
    },

    // ==================== MEAL SELECTION ====================
    mealSelection: {
      loadingMeals: 'Loading meals...',
      selectionOpen: 'Selection Window Open',
      untilDeadline: 'until deadline',
      selectionClosed: 'Selection Window Closed',
      selectionClosedDesc: 'Come back before 8:00 PM to select meals for the next day',
      selectedMeals: 'Selected Meals',
      noMealsSelected: 'No meals selected yet',
      noMealsSelectedShort: 'No meals selected',
      allMealsSelected: 'All meals selected',
      upcomingMeals: 'Upcoming Meals',
      noMealPlans: 'No meal plans yet',
      delivered: 'Delivered',
      preparing: 'Preparing',
      onTheWay: 'On the Way',
      pending: 'Pending',
      scheduled: 'Scheduled',
      deliveredAt: 'Delivered at',
      estimatedDelivery: 'Estimated delivery:',
      tapToSelect: 'Tap to select meals',
      tapToModify: 'Tap to modify',
      confirmSelection: 'Confirm Meal Selection',
      failedLoadMeals: 'Failed to load meal data. Please try again.',
      selectionClosedAlert: 'The selection window for this date has closed.',
      limitReached: 'Limit Reached',
      canOnlySelect: 'You can only select',
      meals: 'meal(s).',
      incompleteSelection: 'Incomplete Selection',
      selectAllRequired: 'Please select all required meals before submitting.',
      confirmMealsFor: 'Confirm meals for',
      mealsConfirmed: 'Your meals have been confirmed!',
      failedSaveMeals: 'Failed to save meal selection.',
      failedSaveMealsRetry: 'Failed to save meal selection. Please try again.',
      h: 'h',
      m: 'm',
    },

    // ==================== CHECKOUT ====================
    checkout: {
      orderSummary: 'Order Summary',
      deliveryAddress: 'Delivery Address',
      checkingZone: 'Checking delivery zone...',
      inDeliveryZone: 'In delivery zone',
      outOfZone: 'This area is out of our delivery zone. Please select a different address.',
      noAddressSelected: 'No address selected',
      payNow: 'Pay Now',
      payWithCard: 'Pay with Card',
      priceDetails: 'Price Details',
      packagePrice: 'Package Price',
      deliveryFee: 'Delivery Fee',
      tax: 'Tax (15%)',
      totalAmount: 'Total Amount',
      outOfZoneBottom: 'Selected address is out of delivery zone',
      addressRequired: 'Address Required',
      selectAddressFirst: 'Please select a delivery address before proceeding.',
      outOfDeliveryZone: 'Out of Delivery Zone',
      outOfZoneAlert: 'This area is out of our delivery zone. Please select a different address.',
    },

    // ==================== PAYMENT ====================
    payment: {
      payWithCard: 'Pay with Card',
      processing: 'Processing payment...',
      amount: 'Amount:',
      paymentFailed: 'Payment Failed',
      paymentFailedMsg: 'Payment failed.',
      paymentStatus: 'Payment Status',
      somethingWrong: 'Something went wrong',
      failedPlaceOrder: 'Failed to place order. Please try again.',
    },

    // ==================== ORDER CONFIRMATION ====================
    orderConfirmation: {
      orderConfirmed: 'Order Confirmed!',
      subscriptionActivated: 'Your subscription has been successfully activated',
      subscriptionId: 'Subscription ID',
      subscriptionDetails: 'Subscription Details',
      package: 'Package',
      plan: 'Plan',
      duration: 'Duration',
      meals: 'Meals',
      startDate: 'Start Date',
      endDate: 'End Date',
      deliveryAddress: 'Delivery Address',
      paymentSummary: 'Payment Summary',
      packagePrice: 'Package Price',
      deliveryFee: 'Delivery Fee',
      totalPaid: 'Total Paid',
      paidVia: 'Paid via',
      creditCard: 'Credit Card',
      whatsNext: "What's Next?",
      firstDelivery: 'Your first delivery will arrive on',
      selectMealsNote: 'Head to "Select Meals" to choose your daily meals before 8:00 PM',
      notifyNote: "We'll notify you when your meals are on the way",
      backToHome: 'Back to Home',
      viewSubscription: 'View Subscription',
    },

    // ==================== ADDRESS ====================
    address: {
      loadingAddresses: 'Loading addresses...',
      noAddresses: 'No Addresses Yet',
      noAddressesDesc: 'Add your first delivery address to get started',
      home: 'Home',
      work: 'Work',
      other: 'Other',
      building: 'Building',
      apt: 'Apt',
      note: 'Note:',
      setPrimary: 'Set Primary',
      addNewAddress: 'Add New Address',
      deleteAddress: 'Delete Address',
      deleteAddressConfirm: 'Are you sure you want to delete this',
      addressQuestion: 'address?',
      failedDeleteAddress: 'Failed to delete address.',
      failedLoadAddresses: 'Failed to load addresses. Please try again.',
      failedSetPrimary: 'Failed to set primary address.',
      searchLocation: 'Search location...',
      addressType: 'Address Type',
      streetAddress: 'Street Address *',
      enterStreetAddress: 'Enter street address',
      buildingNo: 'Building No.',
      apartmentNo: 'Apartment No.',
      city: 'City *',
      district: 'District',
      postalCode: 'Postal Code',
      deliveryNotes: 'Delivery Notes',
      deliveryNotesPlaceholder: 'Any special instructions for delivery...',
      setAsPrimary: 'Set as primary address',
      updateAddress: 'Update Address',
      saveAddress: 'Save Address',
      required: 'Required',
      enterStreet: 'Please enter a street address.',
      enterCity: 'Please enter a city.',
      failedSaveAddress: 'Failed to save address.',
      failedSaveAddressRetry: 'Failed to save address. Please try again.',
    },

    // ==================== ADDRESS SELECTION ====================
    addressSelection: {
      title: 'Select Delivery Address',
      noAddresses: 'No addresses found. Add a new address to continue.',
      addNewAddress: 'Add New Address',
      confirmAddress: 'Confirm Address',
    },

    // ==================== DELIVERY PREFERENCES ====================
    delivery: {
      deliveryAddress: 'Delivery Address',
      whereDeliver: 'Where should we deliver your meals?',
      preferredTime: 'Preferred Delivery Time',
      whenReceive: 'When would you like to receive your meals?',
      morning: 'Morning',
      morningTime: '7:00 AM - 10:00 AM',
      afternoon: 'Afternoon',
      afternoonTime: '12:00 PM - 3:00 PM',
      evening: 'Evening',
      eveningTime: '6:00 PM - 9:00 PM',
      deliveryDays: 'Delivery Days',
      selectDays: 'Select the days you want deliveries',
      daysTotal: 'days total',
      selectAll: 'Select All',
      sun: 'Sun',
      mon: 'Mon',
      tue: 'Tue',
      wed: 'Wed',
      thu: 'Thu',
      fri: 'Fri',
      sat: 'Sat',
      perWeek: 'per week',
      estimated: 'Estimated',
      week: 'week',
      weeks: 'weeks',
      ofDeliveries: 'of deliveries',
      canSkip: 'You can skip up to',
      continueToCheckout: 'Continue to Checkout',
      addressRequired: 'Address Required',
      selectOrAddAddress: 'Please select or add a delivery address.',
      failedLoadAddresses: 'Failed to load addresses.',
    },

    // ==================== PAYMENT METHOD ====================
    paymentMethod: {
      selectPaymentMethod: 'Select Payment Method',
      applePay: 'Apple Pay',
      expires: 'Expires',
      default: 'Default',
      addNewCard: 'Add New Card',
      confirmPaymentMethod: 'Confirm Payment Method',
      cardNumber: 'Card Number',
      cardholderName: 'Cardholder Name',
      expiryDate: 'Expiry Date',
      cvv: 'CVV',
      securePayment: 'Your payment information is encrypted and secure',
      addCard: 'Add Card',
    },

    // ==================== NAVIGATION ====================
    nav: {
      home: 'Home',
      subscriptions: 'Subscriptions',
      profile: 'Profile',
      chooseYourPlan: 'Choose Your Plan',
      manageSubscription: 'Manage Subscription',
      selectMeals: 'Select Meals',
      deliveryPreferences: 'Delivery Preferences',
      checkout: 'Checkout',
      deliveryAddress: 'Delivery Address',
      paymentMethod: 'Payment Method',
      payWithCard: 'Pay with Card',
      myAddresses: 'My Addresses',
      editAddress: 'Edit Address',
      addAddress: 'Add Address',
      editProfile: 'Edit Profile',
      changePassword: 'Change Password',
    },
  },

  ar: {
    // ==================== COMMON ====================
    common: {
      continue: 'متابعة',
      submit: 'إرسال',
      cancel: 'إلغاء',
      save: 'حفظ',
      loading: 'جاري التحميل...',
      error: 'خطأ',
      success: 'نجاح',
      ok: 'حسناً',
      delete: 'حذف',
      edit: 'تعديل',
      confirm: 'تأكيد',
      back: 'رجوع',
      retry: 'إعادة المحاولة',
      free: 'مجاني',
      sar: 'ر.س',
      male: 'ذكر',
      female: 'أنثى',
      yes: 'نعم',
      no: 'لا',
      days: 'أيام',
      day: 'يوم',
      or: 'أو',
      primary: 'رئيسي',
      active: 'نشط',
      paused: 'متوقف',
      expired: 'منتهي',
      cancelled: 'ملغي',
      show: 'إظهار',
      hide: 'إخفاء',
      cal: 'سعرة',
    },

    // ==================== ONBOARDING ====================
    onboarding: {
      title1: 'وجبات طازجة وصحية',
      subtitle1: 'احصل على وجبات لذيذة ومغذية يتم توصيلها إلى باب منزلك يوميًا',
      title2: 'اشتراكات مرنة',
      subtitle2: 'اختر من بين خطط الوجبات المختلفة التي تناسب نمط حياتك',
      title3: 'تتبع طلباتك',
      subtitle3: 'تتبع في الوقت الفعلي لتحضير وتوصيل وجبتك',
      skip: 'تخطي',
      next: 'التالي',
      getStarted: 'ابدأ الآن',
    },

    // ==================== AUTH ====================
    auth: {
      login: 'تسجيل الدخول',
      signup: 'إنشاء حساب',
      phoneNumber: 'رقم الهاتف',
      enterPhone: 'أدخل رقم هاتفك',
      password: 'كلمة المرور',
      enterPassword: 'أدخل كلمة المرور',
      forgotPassword: 'نسيت كلمة المرور؟',
      dontHaveAccount: 'ليس لديك حساب؟',
      alreadyHaveAccount: 'لديك حساب بالفعل؟',
      continueWithGoogle: 'متابعة مع جوجل',
      continueWithApple: 'متابعة مع أبل',
      fullName: 'الاسم الكامل',
      enterName: 'أدخل اسمك الكامل',
      email: 'البريد الإلكتروني',
      enterEmail: 'أدخل بريدك الإلكتروني',
      confirmPassword: 'تأكيد كلمة المرور',
      agreeTerms: 'أوافق على الشروط والأحكام',
      welcome: 'مرحباً بك في لتسالد',
      enterPhoneSubtitle: 'أدخل رقم هاتفك للمتابعة',
      freshMeals: 'وجبات طازجة، توصيل يومي',
      createAccount: 'أنشئ حسابك للبدء',
      failedSendOtp: 'فشل إرسال رمز التحقق',
      failedSendOtpRetry: 'فشل إرسال رمز التحقق. يرجى المحاولة مرة أخرى.',
    },

    // ==================== OTP ====================
    otp: {
      title: 'أدخل رمز التحقق',
      sentTo: 'لقد أرسلنا رمزاً مكوناً من 6 أرقام إلى',
      resendIn: 'إعادة إرسال الرمز خلال',
      resendCode: 'إعادة إرسال الرمز',
      verify: 'تحقق ومتابعة',
      invalidOtp: 'رمز تحقق غير صالح',
      invalidOtpMessage: 'رمز التحقق غير صالح. يرجى المحاولة مرة أخرى.',
      incorrectOtp: 'رمز التحقق الذي أدخلته غير صحيح.',
      otpResent: 'تم إعادة إرسال رمز التحقق إلى هاتفك',
      failedResend: 'فشل إعادة إرسال رمز التحقق',
      failedResendRetry: 'فشل إعادة إرسال رمز التحقق. يرجى المحاولة مرة أخرى.',
    },

    // ==================== PROFILE ====================
    profile: {
      completeTitle: 'أكمل ملفك الشخصي',
      completeSubtitle: 'ساعدنا في تخصيص تجربة وجباتك',
      fullName: 'الاسم الكامل',
      enterFullName: 'أدخل اسمك الكامل',
      emailAddress: 'البريد الإلكتروني',
      emailPlaceholder: 'your.email@example.com',
      sex: 'الجنس',
      weightKg: 'الوزن (كجم)',
      heightCm: 'الطول (سم)',
      age: 'العمر',
      saveChanges: 'حفظ التغييرات',
      profileUpdated: 'تم تحديث الملف الشخصي بنجاح',
      failedSaveProfile: 'فشل حفظ الملف الشخصي',
      failedSaveProfileRetry: 'فشل حفظ الملف الشخصي. يرجى المحاولة مرة أخرى.',
      failedUpdateProfile: 'فشل تحديث الملف الشخصي',
      failedUpdateProfileRetry: 'فشل تحديث الملف الشخصي. يرجى المحاولة مرة أخرى.',
    },

    // ==================== PREFERENCES ====================
    preferences: {
      subscribingForTitle: 'لمن تشترك؟',
      subscribingForSubtitle: 'دعنا نخصص التجربة لتلبية احتياجاتك',
      forMe: 'لنفسي',
      forMeDesc: 'خطط وجبات مخصصة لأهداف لياقتك البدنية',
      forKids: 'للأطفال',
      forKidsDesc: 'خطط وجبات صحية للأطفال من 2-12 سنة',
      genderTitle: 'ما هو جنسك؟',
      genderSubtitle: 'سنستخدم هذا لحساب احتياجاتك اليومية من السعرات الحرارية',
      allergiesTitle: 'هل لديك أي حساسية غذائية؟',
      goalTitle: 'ما هو هدفك؟',
      eatHealthy: 'أكل صحي',
      eatHealthyDesc: 'لتسهيل تناول الطعام الصحي',
      loseWeight: 'إنقاص الوزن',
      loseWeightDesc: 'معدل آمن وصحي لفقدان الوزن والدهون',
      gainWeight: 'زيادة الوزن',
      gainWeightDesc: 'معدل آمن وصحي لزيادة الوزن',
      buildMuscle: 'بناء العضلات',
      buildMuscleDesc: 'اكتساب القوة مع تقليل اكتساب الدهون',
      maintainWeight: 'الحفاظ على الوزن',
      maintainWeightDesc: 'حافظ على لياقتك بالسعرات المناسبة',
      mealTypeTitle: 'ما نوع الوجبات التي تفضلها؟',
      mealTypeSubtitle: 'ستتمكن من الوصول إلى القائمة الكاملة ولكن اختر واحدة لتخصيص تجربتك',
      balanced: 'متوازن',
      balancedDesc: 'يوفر العناصر الغذائية التي يحتاجها جسمك',
      lowCarb: 'قليل الكربوهيدرات',
      lowCarbDesc: 'قليل الكربوهيدرات، غني بالدهون الصحية والخضروات',
      highProtein: 'عالي البروتين',
      highProteinDesc: 'يعزز قوة العضلات والحيوية بالبروتينات الخالية من الدهون',
      protein: 'بروتين',
      carbs: 'كربوهيدرات',
      fat: 'دهون',
      complete: 'إكمال',
      failedSavePreferences: 'فشل حفظ التفضيلات',
      failedSavePreferencesRetry: 'فشل حفظ التفضيلات. يرجى المحاولة مرة أخرى.',
    },

    // ==================== PROFILE SCREEN (Menu) ====================
    profileScreen: {
      editProfile: 'تعديل الملف الشخصي',
      changePassword: 'تغيير كلمة المرور',
      deliveryAddress: 'عنوان التوصيل',
      paymentMethods: 'طرق الدفع',
      helpSupport: 'المساعدة والدعم',
      termsConditions: 'الشروط والأحكام',
      privacyPolicy: 'سياسة الخصوصية',
      deleteAccount: 'حذف الحساب',
      logout: 'تسجيل الخروج',
      language: 'اللغة',
      deleteAccountTitle: 'حذف الحساب',
      deleteAccountMessage: 'هل أنت متأكد من حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.',
      failedDeleteAccount: 'فشل حذف الحساب.',
    },

    // ==================== CHANGE PASSWORD ====================
    changePassword: {
      currentPassword: 'كلمة المرور الحالية',
      enterCurrentPassword: 'أدخل كلمة المرور الحالية',
      newPassword: 'كلمة المرور الجديدة',
      enterNewPassword: 'أدخل كلمة المرور الجديدة',
      confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
      confirmNewPasswordPlaceholder: 'تأكيد كلمة المرور الجديدة',
      passwordsNoMatch: 'كلمات المرور غير متطابقة',
      newPasswordsNoMatch: 'كلمات المرور الجديدة غير متطابقة',
      passwordMinLength: 'يجب أن تتكون كلمة المرور الجديدة من 6 أحرف على الأقل',
      changePassword: 'تغيير كلمة المرور',
      passwordChanged: 'تم تغيير كلمة المرور بنجاح',
      failedChangePassword: 'فشل تغيير كلمة المرور',
      failedChangePasswordRetry: 'فشل تغيير كلمة المرور. يرجى المحاولة مرة أخرى.',
    },

    // ==================== MENU ====================
    menu: {
      title: 'القائمة',
      subtitle: 'اختر وجباتك المفضلة',
      loadingMenu: 'جاري تحميل القائمة...',
      noItems: 'لا توجد وجبات متاحة',
      subscribe: 'اشترك بـ',
    },

    // ==================== SUBSCRIPTIONS ====================
    subscription: {
      mySubscriptions: 'اشتراكاتي',
      loadingSubscriptions: 'جاري تحميل اشتراكاتك...',
      noSubscriptions: 'لا توجد اشتراكات نشطة',
      noSubscriptionsDesc: 'ليس لديك أي اشتراكات نشطة بعد.',
      chooseToStart: 'اختر خطة للبدء!',
      chooseSubscription: 'اختر اشتراكاً',
      manageSubtitle: 'إدارة خطط وجباتك النشطة',
      plan: 'الخطة:',
      mealsRemaining: 'الوجبات المتبقية:',
      daysRemaining: 'الأيام المتبقية:',
      manageSubscription: 'إدارة الاشتراك',
      addMore: '+ إضافة اشتراكات أخرى',
      failedLoadSubscriptions: 'فشل تحميل الاشتراكات. يرجى المحاولة مرة أخرى.',
    },

    // ==================== SUBSCRIPTION PACKAGES ====================
    packages: {
      title: 'اختر خطتك',
      subtitle: 'اختر باقة اشتراك تناسب نمط حياتك',
      loadingPackages: 'جاري تحميل الباقات...',
      noPackages: 'لا توجد باقات متاحة لهذه الخطة',
      recommended: 'موصى به',
      includes: 'يشمل:',
      selectPlan: 'اختر الخطة',
      failedLoadPackages: 'فشل تحميل خطط الاشتراك. يرجى المحاولة مرة أخرى.',
    },

    // ==================== MANAGE SUBSCRIPTION ====================
    manageSubscription: {
      loadingSubscription: 'جاري تحميل الاشتراك...',
      subscriptionPaused: 'الاشتراك متوقف',
      resumesIn: 'يستأنف خلال',
      on: 'في',
      subscriptionDetails: 'تفاصيل الاشتراك',
      package: 'الباقة',
      plan: 'الخطة',
      duration: 'المدة',
      daysRemaining: 'الأيام المتبقية',
      mealsRemaining: 'الوجبات المتبقية',
      startDate: 'تاريخ البدء',
      endDate: 'تاريخ الانتهاء',
      pauseDaysUsed: 'أيام التوقف المستخدمة',
      status: 'الحالة',
      deliveryInfo: 'معلومات التوصيل',
      deliveryAddress: 'عنوان التوصيل',
      deliveryZone: 'منطقة التوصيل',
      payment: 'الدفع',
      mealPlanning: 'تخطيط الوجبات',
      selectMeals: 'اختر وجباتك',
      selectMealsDesc: 'اختر وجبات الأيام الخمسة القادمة',
      mealUpdateNote: 'يمكنك تحديث اختيارات الوجبات حتى الساعة 8:00 مساءً في اليوم السابق للتوصيل',
      actions: 'الإجراءات',
      pauseSubscription: 'إيقاف الاشتراك',
      pauseDaysUsedAction: 'أيام توقف مستخدمة',
      resumeSubscription: 'استئناف الاشتراك',
      resumeDesc: 'استأنف التوصيل الآن',
      failedLoadDetails: 'فشل تحميل تفاصيل الاشتراك.',
      pauseLimitReached: 'تم الوصول لحد الإيقاف',
      pauseLimitMessage: 'لقد استخدمت جميع',
      pauseDaysForSub: 'أيام التوقف لهذا الاشتراك.',
      youHave: 'لديك',
      pauseRemaining: 'متبقية',
      subscriptionPausedFor: 'تم إيقاف اشتراكك لمدة',
      failedPause: 'فشل إيقاف الاشتراك.',
      failedPauseRetry: 'فشل إيقاف الاشتراك. يرجى المحاولة مرة أخرى.',
      subscriptionResumed: 'تم استئناف الاشتراك',
      subscriptionActive: 'اشتراكك نشط مرة أخرى.',
      failedResume: 'فشل استئناف الاشتراك.',
      failedResumeRetry: 'فشل استئناف الاشتراك. يرجى المحاولة مرة أخرى.',
    },

    // ==================== MEAL SELECTION ====================
    mealSelection: {
      loadingMeals: 'جاري تحميل الوجبات...',
      selectionOpen: 'نافذة الاختيار مفتوحة',
      untilDeadline: 'حتى الموعد النهائي',
      selectionClosed: 'نافذة الاختيار مغلقة',
      selectionClosedDesc: 'عد قبل الساعة 8:00 مساءً لاختيار وجبات اليوم التالي',
      selectedMeals: 'الوجبات المختارة',
      noMealsSelected: 'لم يتم اختيار وجبات بعد',
      noMealsSelectedShort: 'لم يتم اختيار وجبات',
      allMealsSelected: 'تم اختيار جميع الوجبات',
      upcomingMeals: 'الوجبات القادمة',
      noMealPlans: 'لا توجد خطط وجبات بعد',
      delivered: 'تم التوصيل',
      preparing: 'قيد التحضير',
      onTheWay: 'في الطريق',
      pending: 'قيد الانتظار',
      scheduled: 'مجدول',
      deliveredAt: 'تم التوصيل في',
      estimatedDelivery: 'التوصيل المتوقع:',
      tapToSelect: 'اضغط لاختيار الوجبات',
      tapToModify: 'اضغط للتعديل',
      confirmSelection: 'تأكيد اختيار الوجبات',
      failedLoadMeals: 'فشل تحميل بيانات الوجبات. يرجى المحاولة مرة أخرى.',
      selectionClosedAlert: 'نافذة الاختيار لهذا التاريخ أُغلقت.',
      limitReached: 'تم الوصول للحد',
      canOnlySelect: 'يمكنك اختيار',
      meals: 'وجبة/وجبات فقط.',
      incompleteSelection: 'اختيار غير مكتمل',
      selectAllRequired: 'يرجى اختيار جميع الوجبات المطلوبة قبل الإرسال.',
      confirmMealsFor: 'تأكيد الوجبات لـ',
      mealsConfirmed: 'تم تأكيد وجباتك!',
      failedSaveMeals: 'فشل حفظ اختيار الوجبات.',
      failedSaveMealsRetry: 'فشل حفظ اختيار الوجبات. يرجى المحاولة مرة أخرى.',
      h: 'س',
      m: 'د',
    },

    // ==================== CHECKOUT ====================
    checkout: {
      orderSummary: 'ملخص الطلب',
      deliveryAddress: 'عنوان التوصيل',
      checkingZone: 'جاري التحقق من منطقة التوصيل...',
      inDeliveryZone: 'ضمن منطقة التوصيل',
      outOfZone: 'هذه المنطقة خارج نطاق التوصيل. يرجى اختيار عنوان آخر.',
      noAddressSelected: 'لم يتم اختيار عنوان',
      payNow: 'ادفع الآن',
      payWithCard: 'الدفع بالبطاقة',
      priceDetails: 'تفاصيل السعر',
      packagePrice: 'سعر الباقة',
      deliveryFee: 'رسوم التوصيل',
      tax: 'الضريبة (15%)',
      totalAmount: 'المبلغ الإجمالي',
      outOfZoneBottom: 'العنوان المحدد خارج منطقة التوصيل',
      addressRequired: 'العنوان مطلوب',
      selectAddressFirst: 'يرجى اختيار عنوان توصيل قبل المتابعة.',
      outOfDeliveryZone: 'خارج منطقة التوصيل',
      outOfZoneAlert: 'هذه المنطقة خارج نطاق التوصيل. يرجى اختيار عنوان آخر.',
    },

    // ==================== PAYMENT ====================
    payment: {
      payWithCard: 'الدفع بالبطاقة',
      processing: 'جاري معالجة الدفع...',
      amount: 'المبلغ:',
      paymentFailed: 'فشل الدفع',
      paymentFailedMsg: 'فشل الدفع.',
      paymentStatus: 'حالة الدفع',
      somethingWrong: 'حدث خطأ ما',
      failedPlaceOrder: 'فشل تقديم الطلب. يرجى المحاولة مرة أخرى.',
    },

    // ==================== ORDER CONFIRMATION ====================
    orderConfirmation: {
      orderConfirmed: 'تم تأكيد الطلب!',
      subscriptionActivated: 'تم تفعيل اشتراكك بنجاح',
      subscriptionId: 'رقم الاشتراك',
      subscriptionDetails: 'تفاصيل الاشتراك',
      package: 'الباقة',
      plan: 'الخطة',
      duration: 'المدة',
      meals: 'الوجبات',
      startDate: 'تاريخ البدء',
      endDate: 'تاريخ الانتهاء',
      deliveryAddress: 'عنوان التوصيل',
      paymentSummary: 'ملخص الدفع',
      packagePrice: 'سعر الباقة',
      deliveryFee: 'رسوم التوصيل',
      totalPaid: 'المبلغ المدفوع',
      paidVia: 'تم الدفع عبر',
      creditCard: 'بطاقة ائتمان',
      whatsNext: 'ما التالي؟',
      firstDelivery: 'سيصل أول توصيل لك في',
      selectMealsNote: 'توجه إلى "اختيار الوجبات" لاختيار وجباتك اليومية قبل الساعة 8:00 مساءً',
      notifyNote: 'سنعلمك عندما تكون وجباتك في الطريق',
      backToHome: 'العودة للرئيسية',
      viewSubscription: 'عرض الاشتراك',
    },

    // ==================== ADDRESS ====================
    address: {
      loadingAddresses: 'جاري تحميل العناوين...',
      noAddresses: 'لا توجد عناوين بعد',
      noAddressesDesc: 'أضف أول عنوان توصيل للبدء',
      home: 'المنزل',
      work: 'العمل',
      other: 'أخرى',
      building: 'مبنى',
      apt: 'شقة',
      note: 'ملاحظة:',
      setPrimary: 'تعيين كرئيسي',
      addNewAddress: 'إضافة عنوان جديد',
      deleteAddress: 'حذف العنوان',
      deleteAddressConfirm: 'هل أنت متأكد من حذف عنوان',
      addressQuestion: '؟',
      failedDeleteAddress: 'فشل حذف العنوان.',
      failedLoadAddresses: 'فشل تحميل العناوين. يرجى المحاولة مرة أخرى.',
      failedSetPrimary: 'فشل تعيين العنوان الرئيسي.',
      searchLocation: 'البحث عن موقع...',
      addressType: 'نوع العنوان',
      streetAddress: 'عنوان الشارع *',
      enterStreetAddress: 'أدخل عنوان الشارع',
      buildingNo: 'رقم المبنى',
      apartmentNo: 'رقم الشقة',
      city: 'المدينة *',
      district: 'الحي',
      postalCode: 'الرمز البريدي',
      deliveryNotes: 'ملاحظات التوصيل',
      deliveryNotesPlaceholder: 'أي تعليمات خاصة للتوصيل...',
      setAsPrimary: 'تعيين كعنوان رئيسي',
      updateAddress: 'تحديث العنوان',
      saveAddress: 'حفظ العنوان',
      required: 'مطلوب',
      enterStreet: 'يرجى إدخال عنوان الشارع.',
      enterCity: 'يرجى إدخال المدينة.',
      failedSaveAddress: 'فشل حفظ العنوان.',
      failedSaveAddressRetry: 'فشل حفظ العنوان. يرجى المحاولة مرة أخرى.',
    },

    // ==================== ADDRESS SELECTION ====================
    addressSelection: {
      title: 'اختر عنوان التوصيل',
      noAddresses: 'لا توجد عناوين. أضف عنواناً جديداً للمتابعة.',
      addNewAddress: 'إضافة عنوان جديد',
      confirmAddress: 'تأكيد العنوان',
    },

    // ==================== DELIVERY PREFERENCES ====================
    delivery: {
      deliveryAddress: 'عنوان التوصيل',
      whereDeliver: 'أين تريد توصيل وجباتك؟',
      preferredTime: 'وقت التوصيل المفضل',
      whenReceive: 'متى تريد استلام وجباتك؟',
      morning: 'صباحاً',
      morningTime: '7:00 ص - 10:00 ص',
      afternoon: 'ظهراً',
      afternoonTime: '12:00 م - 3:00 م',
      evening: 'مساءً',
      eveningTime: '6:00 م - 9:00 م',
      deliveryDays: 'أيام التوصيل',
      selectDays: 'اختر الأيام التي تريد التوصيل فيها',
      daysTotal: 'أيام إجمالاً',
      selectAll: 'تحديد الكل',
      sun: 'أحد',
      mon: 'إثنين',
      tue: 'ثلاثاء',
      wed: 'أربعاء',
      thu: 'خميس',
      fri: 'جمعة',
      sat: 'سبت',
      perWeek: 'في الأسبوع',
      estimated: 'تقريباً',
      week: 'أسبوع',
      weeks: 'أسابيع',
      ofDeliveries: 'من التوصيلات',
      canSkip: 'يمكنك تخطي حتى',
      continueToCheckout: 'متابعة للدفع',
      addressRequired: 'العنوان مطلوب',
      selectOrAddAddress: 'يرجى اختيار أو إضافة عنوان توصيل.',
      failedLoadAddresses: 'فشل تحميل العناوين.',
    },

    // ==================== PAYMENT METHOD ====================
    paymentMethod: {
      selectPaymentMethod: 'اختر طريقة الدفع',
      applePay: 'Apple Pay',
      expires: 'تنتهي',
      default: 'افتراضي',
      addNewCard: 'إضافة بطاقة جديدة',
      confirmPaymentMethod: 'تأكيد طريقة الدفع',
      cardNumber: 'رقم البطاقة',
      cardholderName: 'اسم حامل البطاقة',
      expiryDate: 'تاريخ الانتهاء',
      cvv: 'CVV',
      securePayment: 'معلومات الدفع الخاصة بك مشفرة وآمنة',
      addCard: 'إضافة بطاقة',
    },

    // ==================== NAVIGATION ====================
    nav: {
      home: 'الرئيسية',
      subscriptions: 'الاشتراكات',
      profile: 'الملف الشخصي',
      chooseYourPlan: 'اختر خطتك',
      manageSubscription: 'إدارة الاشتراك',
      selectMeals: 'اختر الوجبات',
      deliveryPreferences: 'تفضيلات التوصيل',
      checkout: 'الدفع',
      deliveryAddress: 'عنوان التوصيل',
      paymentMethod: 'طريقة الدفع',
      payWithCard: 'الدفع بالبطاقة',
      myAddresses: 'عناويني',
      editAddress: 'تعديل العنوان',
      addAddress: 'إضافة عنوان',
      editProfile: 'تعديل الملف الشخصي',
      changePassword: 'تغيير كلمة المرور',
    },
  },
};
